# Generated by Django 4.2.30 on 2026-07-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issue_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueproperty',
            name='issue_type',
            field=models.ForeignKey(blank=True, help_text='The work item type this property is scoped to. NULL means the property applies to every work item type in the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_properties', to='db.issuetype'),
        ),
    ]
