# Generated by Django 4.2.30 on 2026-07-22 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_clear_graph_photo_avatars'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mailbox_email', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Service Desk Config',
                'verbose_name_plural': 'Service Desk Configs',
                'db_table': 'service_desk_configs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueEmailThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mailbox_email', models.CharField(max_length=255)),
                ('conversation_id', models.CharField(db_index=True, max_length=512)),
                ('creator_email', models.CharField(max_length=255)),
                ('creator_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.TextField(blank=True)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('last_inbound_graph_message_id', models.CharField(blank=True, max_length=512, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_thread', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Email Thread',
                'verbose_name_plural': 'Issue Email Threads',
                'db_table': 'issue_email_threads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueEmailMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('graph_message_id', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('internet_message_id', models.CharField(blank=True, max_length=998, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('subject', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='db.issuecomment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='db.issueemailthread')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Email Message',
                'verbose_name_plural': 'Issue Email Messages',
                'db_table': 'issue_email_messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='servicedeskconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='service_desk_config_unique_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedeskconfig',
            unique_together={('project', 'deleted_at')},
        ),
    ]
