# Generated by Django 4.2.30 on 2026-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_service_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeskconfig',
            name='graph_subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedeskconfig',
            name='graph_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicedeskconfig',
            name='webhook_client_state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
