# Generated by Django 4.2.30 on 2026-07-24 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0132_service_desk_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('workspace', 'Workspace')], default='project', max_length=32)),
                ('applies_to_all_projects', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(blank=True, default='', max_length=127)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partially completed'), ('skipped', 'Skipped')], max_length=32, null=True)),
                ('total_run_count', models.PositiveIntegerField(default=0)),
                ('failed_run_count', models.PositiveIntegerField(default=0)),
                ('total_duration_ms', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_automations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_automations', to='db.project')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
                'db_table': 'automations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AutomationProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_projects', to='db.automation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_automation_links', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_automation_projects', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Automation Project',
                'verbose_name_plural': 'Automation Projects',
                'db_table': 'automation_projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(max_length=127)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='db.automation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_automation_actions', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Automation Action',
                'verbose_name_plural': 'Automation Actions',
                'db_table': 'automation_actions',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='automation',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='scoped_automations', through='db.AutomationProject', to='db.project'),
        ),
        migrations.AddField(
            model_name='automation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='automation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_automations', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partially completed'), ('skipped', 'Skipped')], max_length=32)),
                ('trigger_source', models.CharField(choices=[('event', 'Event'), ('schedule', 'Schedule'), ('manual', 'Manual')], default='event', max_length=32)),
                ('trigger_type', models.CharField(blank=True, default='', max_length=127)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_identifier', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='db.automation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_automation_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_automation_runs', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_automation_runs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Automation Run',
                'verbose_name_plural': 'Automation Runs',
                'db_table': 'automation_runs',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['automation', '-started_at'], name='automation_run_recent_idx'), models.Index(fields=['entity_identifier'], name='automation_run_entity_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='automationproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('automation', 'project'), name='automation_project_unique_when_deleted_at_null'),
        ),
        migrations.AddIndex(
            model_name='automationaction',
            index=models.Index(fields=['automation', 'sort_order'], name='automation_action_order_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['workspace', 'is_enabled'], name='automation_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['project', 'is_enabled'], name='automation_project_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['trigger_type', 'is_enabled'], name='automation_trigger_idx'),
        ),
    ]
