# Generated by Django 5.2.15 on 2026-08-11 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_merge_upstream_django_52'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageIndexEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('property', 'Property'), ('task', 'Task'), ('decision', 'Decision')], default='property', max_length=16)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_index_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='db.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_index_entries', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Index Entry',
                'verbose_name_plural': 'Page Index Entries',
                'db_table': 'page_index_entries',
                'ordering': ('page_id', 'sort_order'),
                'indexes': [models.Index(fields=['workspace', 'kind', 'key'], name='page_index_workspace_kind_key'), models.Index(fields=['page', 'kind'], name='page_index_page_kind')],
            },
        ),
    ]
