# Generated by Django 5.2.15 on 2026-08-12 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_page_index_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('training_key', models.CharField(max_length=100)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_steps', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Training Progress',
                'verbose_name_plural': 'User Training Progresses',
                'db_table': 'user_training_progress',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'training_key', 'deleted_at')},
            },
        ),
        migrations.AddConstraint(
            model_name='usertrainingprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'training_key'), name='training_progress_unique_user_training_key_when_deleted_at_null'),
        ),
    ]
