# Generated by Django 5.2.15 on 2026-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_page_index_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageindexentry',
            name='color',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
