# Generated by Django 5.2.15 on 2026-08-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_applicationinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueproperty',
            name='is_multi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issueproperty',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('USER', 'User')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='issueproperty',
            name='property_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('DECIMAL', 'Decimal'), ('OPTION', 'Option'), ('DATETIME', 'Datetime'), ('BOOLEAN', 'Boolean'), ('RELATION', 'Relation')], default='TEXT', max_length=30),
        ),
    ]
