# Generated by Django 5.2.15 on 2026-08-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0139_work_item_property_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuepropertyvalue',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
