# Generated by Django 5.2.15 on 2026-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0141_issue_activity_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_view',
            field=models.BooleanField(default=True),
        ),
    ]
