# Generated by Django 5.2.15 on 2026-09-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0144_dashboard_dashboardwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueproperty",
            name="derivation",
            field=models.CharField(
                choices=[
                    ("NONE", "Manual"),
                    ("INHERIT", "Inherit from parent"),
                    ("LOOKUP", "From ancestor"),
                    ("ROLLUP", "Roll up from children"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issueproperty",
            name="derivation_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="issuepropertyvalue",
            name="is_derived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issuepropertyvalue",
            name="value_issue",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="db.issue"
            ),
        ),
        migrations.AlterField(
            model_name="issueproperty",
            name="relation_type",
            field=models.CharField(
                blank=True, choices=[("USER", "User"), ("ISSUE", "Work item")], max_length=30, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="issuepropertyvalue",
            index=models.Index(fields=["property", "value_issue"], name="issue_prop_value_ref_idx"),
        ),
    ]
