/**
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import { useEffect, useMemo, useRef, useState } from "react";
import type { KeyboardEvent } from "react";
import { NodeViewWrapper, ReactNodeViewRenderer } from "@tiptap/react";
import type { NodeViewProps } from "@tiptap/react";
import { renderToString } from "katex";
// local imports
import { MathBlockExtensionConfig, MathInlineExtensionConfig } from "./extension-config";

const renderLatex = (latex: string, displayMode: boolean): string => {
  if (!latex) return "";
  return renderToString(latex, {
    throwOnError: false,
    displayMode,
    output: "htmlAndMathml",
  });
};

function MathNodeView(props: NodeViewProps & { displayMode: boolean }) {
  const { displayMode, editor, node, updateAttributes } = props;
  const latex: string = node.attrs.latex ?? "";
  const isEditable = editor.isEditable;

  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState(latex);
  const skipBlurCommitRef = useRef(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const renderedLatex = useMemo(() => renderLatex(latex, displayMode), [latex, displayMode]);
  const renderedDraft = useMemo(() => renderLatex(draft, displayMode), [draft, displayMode]);

  useEffect(() => {
    if (isEditing) textareaRef.current?.focus();
  }, [isEditing]);

  const commit = () => {
    updateAttributes({ latex: draft });
    setIsEditing(false);
  };

  const cancel = () => {
    skipBlurCommitRef.current = true;
    setDraft(latex);
    setIsEditing(false);
  };

  const handleBlur = () => {
    if (skipBlurCommitRef.current) {
      skipBlurCommitRef.current = false;
      return;
    }
    commit();
  };

  const handleTextareaKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === "Escape") {
      event.preventDefault();
      cancel();
    } else if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) {
      event.preventDefault();
      commit();
    }
  };

  const openEditor = () => {
    setDraft(latex);
    setIsEditing(true);
  };

  const wrapperClassName = displayMode ? "editor-math-block-component my-2 block" : "editor-math-inline-component";

  const renderContent = () => {
    if (isEditing) {
      return (
        <span
          className="inline-flex flex-col gap-1.5 rounded-md border border-subtle bg-surface-1 p-2"
          contentEditable={false}
        >
          <textarea
            ref={textareaRef}
            aria-label="LaTeX equation"
            className="font-mono min-w-64 rounded border border-subtle bg-surface-2 px-2 py-1 text-13 text-primary outline-none"
            placeholder="Enter LaTeX"
            rows={displayMode ? 3 : 1}
            value={draft}
            onBlur={handleBlur}
            onChange={(event) => setDraft(event.target.value)}
            onKeyDown={handleTextareaKeyDown}
          />
          {/* KaTeX's output is generated by KaTeX itself from the LaTeX source
              above and holds no user-supplied HTML, so this is safe. The same
              goes for every other dangerouslySetInnerHTML in this file. */}
          {draft && <span className="px-1 text-13" dangerouslySetInnerHTML={{ __html: renderedDraft }} />}
        </span>
      );
    }

    if (!isEditable) {
      return latex ? <span contentEditable={false} dangerouslySetInnerHTML={{ __html: renderedLatex }} /> : null;
    }

    if (!latex) {
      return (
        <button
          type="button"
          className="cursor-pointer rounded border border-dashed border-subtle px-2 py-1 text-13 text-tertiary"
          contentEditable={false}
          onClick={openEditor}
        >
          Click to add an equation
        </button>
      );
    }

    return (
      <button
        type="button"
        // The rendered KaTeX is the button's only content, so the LaTeX source
        // is what names it.
        aria-label={`Edit equation: ${latex}`}
        className="cursor-pointer"
        contentEditable={false}
        onClick={openEditor}
        dangerouslySetInnerHTML={{ __html: renderedLatex }}
      />
    );
  };

  return (
    // NodeViewWrapper needs as="span" for the inline node, or ProseMirror ends
    // up with a block element where it expects inline content.
    <NodeViewWrapper as={displayMode ? undefined : "span"} className={wrapperClassName}>
      {renderContent()}
    </NodeViewWrapper>
  );
}

function MathInline(props: NodeViewProps) {
  return <MathNodeView {...props} displayMode={false} />;
}

function MathBlock(props: NodeViewProps) {
  return <MathNodeView {...props} displayMode />;
}

export const MathInlineExtension = MathInlineExtensionConfig.extend({
  addNodeView() {
    return ReactNodeViewRenderer(MathInline);
  },
});

export const MathBlockExtension = MathBlockExtensionConfig.extend({
  addNodeView() {
    return ReactNodeViewRenderer(MathBlock);
  },
});
